### ISSUE TITLE
Issues running `movies.run.ts`

### ISSUE THREAD

**Issue by clxyder** [hrishioa/wishful-search#12]
Thanks for the great work @hrishioa!

I am running into some issues trying to run the example `movies.run.ts` script.

At first, I ran into the following issue `Property 'queryPrefix' is missing in type`.

This was an easy fix as I just needed to add `"queryPrefix": ""` to `MOVIES_FEW_SHOT` in `movies-data.ts`:

```typescript
{
    "queryPrefix": "",
    "question": "something romantic?",
    "partialQuery": "WHERE id IN (\n    SELECT movie_id FROM Genres WHERE genre_name = 'Romance'\n)"
  },
```

Not sure if an empty `queryPrefix` is correct though.

Now when I run `npx ts-node ./tests/movies.run.ts`, I get the following error:

```
What are you looking for? I want to watch a good comedy movie

Query:  SELECT id FROM Movies WHERE genre_name LIKE '%Comedy%' AND vote_average >= 7.0 ORDER BY popularity DESC, vote_average DESC LIMIT 10
Error in query  WHERE genre_name LIKE '%Comedy%' AND vote_average >= 7.0 ORDER BY popularity DESC, vote_average DESC LIMIT 10  - reflecting and fixing error  Error: no such column: genre_name
    at e.handleError (/repos/wishful-search/node_modules/sql.js/dist/sql-wasm.js:90:245)
    at e.exec (/repos/wishful-search/node_modules/sql.js/dist/sql-wasm.js:87:501)
    at LLMSearcheableDatabase.rawQuery (/repos/wishful-search/src/db.ts:155:28)
    at WishfulSearchEngine.searchWithPartialQuery (/repos/wishful-search/src/search-engine.ts:345:29)
    at WishfulSearchEngine.<anonymous> (/repos/wishful-search/src/search-engine.ts:675:28)
    at Generator.next (<anonymous>)
    at fulfilled (/repos/wishful-search/src/search-engine.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Seems like the database just doesn't have the right columns. Am I missing anything? Does an empty `queryPrefix` break it?

**Comment by hrishioa** [comment]
Really good catch! As I released complex analytics, the queryPrefix was a way to separate both types of queries - did not notice that it broke movies. 

I've released a [new version](https://github.com/hrishioa/wishful-search/commit/611e8305ee4f04751183c2a91bc4f4f81ef45058) that makes this an optional param, so it should work out of the box now!

For the `genre_name` issue, it seems to only be a GPT-3.5 thing. The DDL seems to be set up right, and neither Claude nor GPT-4 (or even Mistral) seem to have that issue on my end - they get the query right the first time. I remember leaving it in GPT-3.5 so you can see how reflection works....

Can you let me know if this is works for you and I'll mark it closed?

**Comment by clxyder** [comment]
That was fast! I will confirm once I get a chance to test it out. 

Although, I'm certain the issue will be fixed!

**Comment by hrishioa** [comment]
No problem! I'll close it for now since I've tested `movies.run.ts` on my end, let me know or reopen if you run into problems!
