### ISSUE TITLE
Open AI API Key

### ISSUE THREAD

**Issue by benfield97** [hrishioa/wishful-search#4]
Hi, 
Apologies for the basic question but I'm not too familiar with typescript. Where do I put my openAI key in the index.ts file?

Would love to try this tool out but can't even get it running with the demo movies script because of this.

**Comment by benfield97** [comment]
for anyone looking

const openai = new OpenAI({
  apiKey: 'My API Key', // defaults to process.env["OPENAI_API_KEY"]
});

this is the syntax to use in whatever file you choose to run the script from

**Comment by hrishioa** [comment]
Yup exactly - kept things relatively simple, so for OpenAI and Anthropic you can also put it into your environment with
`export OPENAI_API_KEY=XXXX npx ts-node ....ts` or similar for anthropic as well. This will be the safest.

**Comment by hrishioa** [comment]
Updated the README with same info.
